# Generated by Django 5.2.8 on 2026-05-25 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="The question text (e.g., 'Introduction')", max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Order in which this question appears')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Optional label for the row (e.g., 'Structure', 'Content')", max_length=200)),
                ('text_positive', models.TextField(help_text='Feedback text for the Positive option')),
                ('text_negative', models.TextField(help_text='Feedback text for the Negative option')),
                ('order', models.IntegerField(default=0, help_text='Order in which this row appears within the question')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='comments_generator.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
