# Generated by Django 5.2.8 on 2026-06-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Theme', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('brand_primary', models.CharField(default='#1a1a2e', help_text='Hex color code (e.g. #1a1a2e)', max_length=7)),
                ('brand_primary_dark', models.CharField(default='#0f172a', help_text='Hex color code (e.g. #0f172a)', max_length=7)),
                ('brand_primary_light', models.CharField(default='#2e2e4a', help_text='Hex color code (e.g. #2e2e4a)', max_length=7)),
                ('brand_accent', models.CharField(default='#c8a951', help_text='Hex color code (e.g. #c8a951)', max_length=7)),
            ],
        ),
    ]
