# Generated by Django 5.2.8 on 2026-06-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeconfig',
            name='brand_accent',
            field=models.CharField(default='#c8a951', help_text='Hex colour code (e.g. #c8a951)', max_length=7),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='brand_primary',
            field=models.CharField(default='#1a1a2e', help_text='Hex colour code (e.g. #1a1a2e)', max_length=7),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='brand_primary_dark',
            field=models.CharField(default='#0f172a', help_text='Hex colour code (e.g. #0f172a)', max_length=7),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='brand_primary_light',
            field=models.CharField(default='#2e2e4a', help_text='Hex colour code (e.g. #2e2e4a)', max_length=7),
        ),
    ]
