# Generated by Django 6.0.2 on 2026-02-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Optional label for the row (e.g., 'Introduction', 'Methodology')", max_length=200)),
                ('text_positive', models.TextField(help_text='Feedback text for the Positive option')),
                ('text_negative', models.TextField(help_text='Feedback text for the Negative option')),
                ('order', models.IntegerField(default=0, help_text='Order in which this row appears on the form')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
