# Generated by Django 5.2.8 on 2026-02-17 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="The question text (e.g., 'Introduction')", max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Order in which this question appears')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='feedbackrow',
            name='label',
            field=models.CharField(blank=True, help_text="Optional label for the row (e.g., 'Structure', 'Content')", max_length=200),
        ),
        migrations.AlterField(
            model_name='feedbackrow',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in which this row appears within the question'),
        ),
        migrations.AddField(
            model_name='feedbackrow',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='feedback_generator.question'),
        ),
    ]
