# Generated by Django 5.2.8 on 2025-11-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('module_code', models.CharField(max_length=50)),
                ('assessment_title', models.CharField(max_length=200)),
                ('categories', models.JSONField(default=list)),
            ],
        ),
    ]
