# Generated by Django 5.2.8 on 2025-11-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttemplate',
            name='component',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
