# Generated by Django 5.2.8 on 2025-11-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_assessmenttemplate_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttemplate',
            name='component',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
