# Generated by Django 5.2.8 on 2025-11-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_assessmenttemplate_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttemplate',
            name='module_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
