# Generated by Django 5.2.8 on 2025-11-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_assessmenttemplate_module_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttemplate',
            name='weighting',
            field=models.IntegerField(blank=True, help_text='Assessment weighting as percentage (e.g., 40 for 40%)', null=True),
        ),
    ]
