# Generated by Django 5.2.8 on 2025-11-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_assessmenttemplate_weighting'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttemplate',
            name='max_marks',
            field=models.IntegerField(blank=True, help_text='Maximum marks for the assessment (e.g., 100)', null=True),
        ),
    ]
