# Generated by Django 5.2.8 on 2025-11-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_assessmenttemplate_max_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttemplate',
            name='charts',
            field=models.JSONField(blank=True, default=list, help_text='Chart configurations for feedback sheet (e.g., histograms, radar charts)'),
        ),
    ]
