# Generated by Django 5.2.8 on 2025-11-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_assessmenttemplate_charts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttemplate',
            name='max_marks',
            field=models.IntegerField(default=100, help_text='Maximum marks for the assessment (e.g., 100)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessmenttemplate',
            name='module_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmenttemplate',
            name='weighting',
            field=models.IntegerField(default=100, help_text='Assessment weighting as percentage (e.g., 40 for 40%)'),
            preserve_default=False,
        ),
    ]
