# Generated by Django 5.2.8 on 2025-11-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_alter_assessmenttemplate_max_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttemplate',
            name='degree_level',
            field=models.CharField(choices=[('BEng', 'BEng'), ('MEng', 'MEng')], default='BEng', max_length=10, help_text='Degree level (BEng or MEng/MSc)'),
            preserve_default=False,
        ),
    ]
