# Generated by Django 5.2.8 on 2026-02-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_assessmenttemplate_degree_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttemplate',
            name='degree_level',
            field=models.CharField(choices=[('BEng', 'BEng'), ('MEng/MSc', 'MEng/MSc')], default='BEng', help_text='Degree level (BEng or MEng/MSc)', max_length=10),
        ),
    ]
