"""Matplotlib-based server-side SVG chart generation utilities."""
import io
import numpy as np
import matplotlib
# Use non-interactive Agg backend to avoid GUI threads/issues
matplotlib.use('Agg')
# Render native SVG text elements for smaller file sizes and tooltip manipulation
matplotlib.rcParams['svg.fonttype'] = 'none'
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator


def inject_svg_tooltips(svg_str):
    """
    Finds <a xlink:href="tooltip:..."> wrappers generated by Matplotlib url properties
    and converts them to <g> elements with nested <title> tooltips.
    """
    import re
    pattern = r'<a\s+[^>]*?(?:xlink:)?href="tooltip:([^"]+)"[^>]*?>\s*(.*?)\s*</a>'
    
    def repl(match):
        tooltip_text = match.group(1)
        inner_content = match.group(2)
        return f'<g>\n<title>{tooltip_text}</title>\n{inner_content}\n</g>'
        
    return re.sub(pattern, repl, svg_str, flags=re.DOTALL)


def generate_radar_chart(categories, student_percentages, average_percentages, pass_mark=40):
    """
    Generate a radar chart with a straight-sided (polygon) grid comparing a
    student's marks against the class average in percentage terms (0-100%).

    Uses a manual polygon-based approach so grid rings are diamond/square
    shaped rather than circular, matching the reference style.

    Args:
        categories: List of category label strings
        student_percentages: List of student percentages matching the categories
        average_percentages: List of class average percentages matching the categories
        pass_mark: Pass threshold percentage — drawn as a red dashed polygon ring.
                   Use 40 for UG, 50 for M-level. Defaults to 40.

    Returns:
        str: SVG XML string representing the vector chart
    """
    num_vars = len(categories)
    if num_vars == 0:
        return ""

    # Angles for each axis, starting from top (90 degrees) going clockwise
    angles = np.linspace(np.pi / 2, np.pi / 2 + 2 * np.pi, num_vars, endpoint=False)

    def polar_to_xy(r, theta):
        return r * np.cos(theta), r * np.sin(theta)

    def make_polygon(values, angles, scale=1.0):
        """Convert percentage values to (x, y) polygon points, normalised to scale."""
        xs, ys = [], []
        for v, a in zip(values, angles):
            r = (v / 100.0) * scale
            x, y = polar_to_xy(r, a)
            xs.append(x)
            ys.append(y)
        xs.append(xs[0])
        ys.append(ys[0])
        return xs, ys

    # Colours
    student_color = '#74c476'   # Green — matches histogram 1st colour
    average_color = '#7bafd4'   # Blue — matches histogram 2:2 colour
    grid_color    = '#cccccc'
    label_color   = '#1e293b'
    scale = 1.0  # unit circle radius

    fig, ax = plt.subplots(figsize=(5.5, 5.5))
    ax.set_aspect('equal')
    ax.axis('off')

    # Draw polygon grid rings at 20, 40, 60, 80, 100%
    for level in [0.2, 0.4, 0.6, 0.8, 1.0]:
        ring_xs, ring_ys = make_polygon([level * 100] * num_vars, angles, scale)
        ax.plot(ring_xs, ring_ys, color=grid_color, linewidth=0.8, zorder=1)
        # Label the ring on the first axis
        label_x, label_y = polar_to_xy(level * scale, angles[0])
        ax.text(label_x, label_y, f'{int(level * 100)}',
                ha='center', va='bottom', fontsize=9, color='#888888')

    # Draw axis spokes
    for a in angles:
        x, y = polar_to_xy(scale, a)
        ax.plot([0, x], [0, y], color=grid_color, linewidth=0.8, zorder=1)

    # Draw pass mark threshold ring — red dashed polygon
    pass_xs, pass_ys = make_polygon([pass_mark] * num_vars, angles, scale)
    ax.plot(pass_xs, pass_ys, color='#d9534f', linewidth=1.5,
            linestyle='--', zorder=2, label=f'Pass Mark ({pass_mark}%)')

    # Draw class average polygon
    avg_xs, avg_ys = make_polygon(list(average_percentages), angles, scale)
    ax.fill(avg_xs, avg_ys, color=average_color, alpha=0.25, zorder=2)
    ax.plot(avg_xs, avg_ys, color=average_color, linewidth=2.0, zorder=3, label='Class Average')

    # Draw student polygon
    stu_xs, stu_ys = make_polygon(list(student_percentages), angles, scale)
    ax.fill(stu_xs, stu_ys, color=student_color, alpha=0.25, zorder=4)
    ax.plot(stu_xs, stu_ys, color=student_color, linewidth=2.0, zorder=5, label='Your Mark')

    # Category labels — truncate at 14 chars, positioned just outside outer ring
    for i, (cat, a) in enumerate(zip(categories, angles)):
        x_raw, y_raw = polar_to_xy(scale, a)
        # Apply separate x and y offsets so horizontal labels sit closer
        lx = x_raw * 1.05
        ly = y_raw * 1.22
        ha = 'center'
        if x_raw < -0.1: ha = 'right'
        elif x_raw > 0.1: ha = 'left'
        label = cat if len(cat) <= 7 else cat[:6] + '…'
        ax.text(lx, ly, label, ha=ha, va='center',
                fontsize=11, color=label_color, fontweight='semibold',
                fontfamily='DejaVu Sans')

    # Legend at the bottom, horizontal
    ax.legend(
        loc='upper center',
        bbox_to_anchor=(0.5, -0.02),
        ncol=3,
        fontsize=11,
        frameon=False,
        handlelength=1.5,
    )

    ax.set_xlim(-1.4, 1.4)
    ax.set_ylim(-1.4, 1.4)

    fig.patch.set_facecolor('white')

    buf = io.BytesIO()
    plt.savefig(buf, format='svg', bbox_inches='tight', transparent=False)
    plt.close(fig)

    svg_data = buf.getvalue().decode('utf-8')

    # Post-process SVG to inject mouseover tooltips (<title> tags) on radar category labels
    import html
    import re
    for cat in categories:
        short_label = cat if len(cat) <= 7 else cat[:6] + '…'
        escaped_label = re.escape(short_label)
        pattern = re.compile(rf'(<text\b[^>]*>)({escaped_label})(</text>)')
        svg_data = pattern.sub(rf'\1<title>{html.escape(cat)}</title>\2\3', svg_data, count=1)

    return svg_data


def generate_cohort_histogram(scores, student_score=None, degree_level=None):
    """
    Generate a cohort mark distribution histogram using percentage-based bins,
    coloured by UK grade band, with a dashed vertical line for the student's mark.

    Args:
        scores: List of all student marks (already converted to percentages) in the cohort
        student_score: The specific student's mark (already converted to percentage) or None to omit
        degree_level: The degree level (e.g. 'BEng' or 'MEng/MSc')

    Returns:
        str: SVG XML string representing the vector chart
    """
    if not scores:
        return ""

    # Determine if postgraduate/M-level (where <50% is a fail)
    is_m_level = bool(
        degree_level 
        and isinstance(degree_level, str) 
        and degree_level.strip().lower().startswith('m')
    )

    # Grade band colours for each 10% bin
    band_colours = {
        0:  '#d9534f',  # Fail
        10: '#d9534f',  # Fail
        20: '#d9534f',  # Fail
        30: '#d9534f',  # Fail
        40: '#d9534f' if is_m_level else '#4a90d9',  # Fail for M-level, 3rd otherwise
        50: '#4a90d9',  # 2:2
        60: '#4a90d9',  # 2:1
        70: '#74c476',  # 1st
        80: '#74c476',  # 1st
        90: '#74c476',  # 1st
    }

    # Separate absent (score == 0) from scored submissions
    ab_scores = [s for s in scores if s == 0]
    scored = [s for s in scores if s > 0]
    ab_count = len(ab_scores)
    has_ab = ab_count > 0

    # AB bar sits in a virtual slot from -12 to -2 (centre at -7), leaving a 2-unit gap before 0
    AB_CENTER = -7
    AB_WIDTH = 8
    X_START = -13 if has_ab else 0

    fixed_bins = list(range(0, 101, 10))

    fig, ax = plt.subplots(figsize=(8.0, 5.0))

    n, bins, patches = ax.hist(
        scored,
        bins=fixed_bins,
        range=(0, 100),
        edgecolor='white',
        linewidth=1.0,
        rwidth=0.85,
    )

    # Colour each bar by its grade band and set URLs for tooltips
    for patch, left_edge, count in zip(patches, fixed_bins[:-1], n):
        patch.set_facecolor(band_colours.get(left_edge, '#74c476'))
        right_edge = left_edge + 10
        if right_edge == 100:
            label = f"90-100%: {int(count)} student{'s' if int(count) != 1 else ''}"
        else:
            label = f"{left_edge}-{right_edge - 1}%: {int(count)} student{'s' if int(count) != 1 else ''}"
        patch.set_url(f"tooltip:{label}")

    # AB bar — dark grey, visually separated
    if has_ab:
        ab_bar = ax.bar(
            AB_CENTER, ab_count,
            width=AB_WIDTH,
            color='#6b7280',
            edgecolor='white',
            linewidth=1.0,
            zorder=3,
        )
        for patch in ab_bar:
            label = f"Absent: {ab_count} student{'s' if ab_count != 1 else ''}"
            patch.set_url(f"tooltip:{label}")

    # Student mark — dashed vertical line with label above (if provided)
    if student_score is not None:
        ax.axvline(student_score, color='#3a3a3a', linestyle='--', linewidth=1.8, zorder=5)
        ax.text(
            student_score + 0.8,
            ax.get_ylim()[1] * 1.1,
            f'Your Mark',
            color='#3a3a3a',
            fontsize=16,
            va='top',
        )

    # Axes
    ax.set_xlim(X_START, 100)
    if has_ab:
        ax.set_xticks([AB_CENTER] + list(range(0, 101, 10)))
        ax.set_xticklabels(['AB'] + [str(i) for i in range(0, 101, 10)])
    else:
        ax.set_xticks(range(0, 101, 10))
    ax.set_xlabel('Mark (%)', color='#475569', size=16, fontfamily='DejaVu Sans')
    ax.set_ylabel('Number of Students', color='#475569', size=16, fontfamily='DejaVu Sans')

    # Y-axis: integer ticks only, at most ~8 sensible intervals
    ax.yaxis.set_major_locator(MaxNLocator(integer=True, nbins=8, min_n_ticks=3))

    # Spines — all four visible to form a box
    for spine in ax.spines.values():
        spine.set_visible(True)
        spine.set_color('#cbd5e1')

    ax.tick_params(axis='both', which='both', length=0, colors='#475569', labelsize=16)
    ax.set_facecolor('white')
    fig.patch.set_facecolor('white')

    buf = io.BytesIO()
    plt.savefig(buf, format='svg', bbox_inches='tight', transparent=False)
    plt.close(fig)

    return inject_svg_tooltips(buf.getvalue().decode('utf-8'))


def generate_module_comparison_chart(labels, student_percentages, average_percentages):
    """
    Generate a high-fidelity vector grouped bar chart comparing a student's percentage marks
    against the class average percentages for both assessment components.
    
    Args:
        labels: List of component label strings (e.g. ['Assessment 1', 'Assessment 2'])
        student_percentages: Student percentages for the components
        average_percentages: Class average percentages for the components
        
    Returns:
        str: SVG XML string representing the vector chart
    """
    if not labels:
        return ""
        
    fig, ax = plt.subplots(figsize=(5.5, 3.2))
    
    x = np.arange(len(labels))
    width = 0.30  # width of the bars
    
    student_color = '#4361ee'  # Indigo/Blue
    average_color = '#ff006e'  # Harmonious Pink/Red
    grid_color = '#cbd5e1'
    text_color = '#1e293b'
    
    # Plot bars
    ax.bar(x - width/2, student_percentages, width, label='Your Score', color=student_color, alpha=0.9, edgecolor='none', zorder=3)
    ax.bar(x + width/2, average_percentages, width, label='Class Average', color=average_color, alpha=0.5, edgecolor='none', zorder=3)
    
    # Styling
    ax.set_ylabel('Percentage (%)', color=text_color, fontweight='semibold', size=9.5)
    ax.set_xticks(x)
    ax.set_xticklabels(labels, color=text_color, size=9, fontweight='semibold')
    ax.set_ylim(0, 100)
    
    # Grid lines
    ax.grid(True, axis='y', color=grid_color, linestyle=':', linewidth=0.8, zorder=0)
    ax.set_axisbelow(True)
    
    # Spines
    for spine in ['top', 'right', 'left']:
        ax.spines[spine].set_visible(False)
    ax.spines['bottom'].set_color('#cbd5e1')
    
    ax.tick_params(axis='both', which='both', length=0, colors='#475569', labelsize=8.5)
    
    # Legend
    plt.legend(loc='upper right', fontsize=8.5, frameon=True, facecolor='white', edgecolor='#e2e8f0')
    
    buf = io.BytesIO()
    plt.savefig(buf, format='svg', bbox_inches='tight', transparent=True)
    plt.close(fig)
    
    return buf.getvalue().decode('utf-8')


def clean_svg(svg_str):
    """Strips XML prolog to make Matplotlib's output safe for inline SVG nesting."""
    import re
    if not svg_str:
        return ""
    match = re.search(r'<svg.*', svg_str, re.DOTALL)
    if match:
        return match.group(0)
    return svg_str


def generate_programme_comparison_chart(modules_data, metric='mean'):
    """Generates an SVG bar chart comparing a specific metric across multiple modules."""
    if not modules_data:
        return ""
    
    codes = [m["module_code"] for m in modules_data]
    
    # Extract values and labels based on metric
    if metric == 'std_dev':
        values = [m.get("std_dev", 0.0) for m in modules_data]
        ylabel = 'Standard Deviation'
        tooltip_suffix = 'std dev'
    elif metric == 'pct_1st':
        values = [m.get("pct_1st", 0.0) for m in modules_data]
        ylabel = '1st Class (%)'
        tooltip_suffix = '% 1st Class'
    elif metric == 'pct_21_above':
        values = [m.get("pct_21_above", 0.0) for m in modules_data]
        ylabel = '2:1 & Above (%)'
        tooltip_suffix = '% 2:1 & above'
    elif metric == 'pct_fail':
        values = [m.get("pct_fail", 0.0) for m in modules_data]
        ylabel = 'Fail (%)'
        tooltip_suffix = '% Fail'
    else:  # default to mean
        values = [m.get("mean", 0.0) for m in modules_data]
        ylabel = 'Mean Score (%)'
        tooltip_suffix = '% mean'
    
    # Calculate chart width dynamically (0.6 inches per module code, minimum 12.0)
    chart_width = max(12.0, 0.6 * len(codes))
    fig, ax = plt.subplots(figsize=(chart_width, 4.0))
    
    level_colors = {
        3: '#cbd5e1',
        4: '#10b981',
        5: '#3b82f6',
        6: '#8b5cf6',
        7: '#f59e0b',
    }
    colors_list = [level_colors.get(m.get("level", 4), '#3b82f6') for m in modules_data]
    
    x = np.arange(len(codes))
    bars = ax.bar(x, values, width=0.4, color=colors_list, alpha=0.9, edgecolor='none', zorder=3)
    
    # Set tooltips for each bar
    for bar, code, val in zip(bars, codes, values):
        if metric == 'std_dev':
            bar.set_url(f"tooltip:{code}: {val:.1f} std dev")
        elif metric == 'pct_1st':
            bar.set_url(f"tooltip:{code}: {val:.1f}% 1st Class")
        elif metric == 'pct_21_above':
            bar.set_url(f"tooltip:{code}: {val:.1f}% 2:1 & above")
        elif metric == 'pct_fail':
            bar.set_url(f"tooltip:{code}: {val:.1f}% Fail")
        else:
            bar.set_url(f"tooltip:{code}: {val:.1f}% mean")
    
    ax.set_ylabel(ylabel, color='#475569', size=11, fontfamily='DejaVu Sans')
    ax.set_xticks(x)
    ax.set_xticklabels(codes, color='#475569', size=10, fontfamily='DejaVu Sans', rotation=15, ha='right')
    
    if metric == 'std_dev':
        max_v = max(values) if values else 0
        ax.set_ylim(0, max(25, max_v * 1.15))
    else:
        ax.set_ylim(0, 100)
    
    ax.grid(True, axis='y', color='#e2e8f0', linestyle=':', linewidth=0.8, zorder=0)
    ax.set_axisbelow(True)
    
    for spine in ['top', 'right', 'left']:
        ax.spines[spine].set_visible(False)
    ax.spines['bottom'].set_color('#cbd5e1')
    
    ax.tick_params(axis='both', which='both', length=0, colors='#475569', labelsize=10)
    ax.set_facecolor('white')
    fig.patch.set_facecolor('white')
    
    buf = io.BytesIO()
    plt.savefig(buf, format='svg', bbox_inches='tight', transparent=False)
    plt.close(fig)
    
    return clean_svg(inject_svg_tooltips(buf.getvalue().decode('utf-8')))


def generate_line_chart(
    x_labels,
    series_list,
    ylabel,
    title,
    figsize=(10.0, 4.5),
    ylim=None,
    grid_axis='both',
    grid_style='--',
    legend_loc='upper right',
    legend_ncol=1,
    legend_bbox_to_anchor=None,
    rotation=0,
    ha='center',
    fontsize_xticks=9.5,
    fontsize_yticks=9.5,
    fontsize_ylabel=11.0,
    fontsize_title=12.0,
    pad_title=15,
):
    """
    Core generic line chart generator used for all line charts in the application.
    """
    fig, ax = plt.subplots(figsize=figsize)
    x = np.arange(len(x_labels))
    
    for s in series_list:
        y_vals = s['y_values']
        label = s.get('label')
        color = s.get('color', '#3b82f6')
        marker = s.get('marker', 'o')
        linewidth = s.get('linewidth', 2.0)
        markersize = s.get('markersize', 5)
        alpha = s.get('alpha', 1.0)
        
        # Plot line
        lines = ax.plot(
            x, y_vals,
            label=label,
            color=color,
            linewidth=linewidth,
            marker=marker,
            markersize=markersize,
            alpha=alpha,
            zorder=4
        )
        
        # Line URL (tooltip)
        if s.get('url'):
            for line in lines:
                line.set_url(s['url'])
                
        # Points markers for individual tooltips
        point_urls = s.get('point_urls', [])
        for xi, yi in zip(x, y_vals):
            if yi is not None:
                # Plot a single marker at (xi, yi) to act as a tooltip target
                pt_line, = ax.plot(
                    [xi], [yi],
                    marker=marker,
                    color=color,
                    markersize=markersize,
                    zorder=5,
                    markeredgecolor=color,
                    alpha=alpha
                )
                # If there are point-specific tooltips, apply them
                if point_urls and xi < len(point_urls) and point_urls[xi]:
                    pt_line.set_url(point_urls[xi])
                    
    ax.set_xticks(x)
    ax.set_xticklabels(x_labels, rotation=rotation, ha=ha, fontsize=fontsize_xticks)
    ax.tick_params(axis='y', labelsize=fontsize_yticks)
    ax.set_ylabel(ylabel, fontsize=fontsize_ylabel, fontweight='semibold', color='#475569')
    if title:
        ax.set_title(title, fontsize=fontsize_title, fontweight='bold', pad=pad_title, color='#1e293b')
        
    if ylim is not None:
        ax.set_ylim(ylim)
        
    ax.grid(True, axis=grid_axis, color='#e2e8f0', linestyle=grid_style, linewidth=0.8, zorder=0)
    ax.set_axisbelow(True)
    
    # Legend
    has_labels = any(s.get('label') for s in series_list)
    if has_labels:
        ax.legend(
            loc=legend_loc,
            bbox_to_anchor=legend_bbox_to_anchor,
            ncol=legend_ncol,
            fontsize=fontsize_xticks,
            frameon=False
        )
        
    # Hide top, right, and left spines to match other charts
    for spine in ['top', 'right', 'left']:
        ax.spines[spine].set_visible(False)
    ax.spines['bottom'].set_color('#cbd5e1')
    
    # Disable tick markers
    ax.tick_params(axis='both', which='both', length=0, colors='#475569')
    ax.set_facecolor('white')
    fig.patch.set_facecolor('white')
    
    buf = io.BytesIO()
    plt.savefig(buf, format='svg', bbox_inches='tight', transparent=False)
    plt.close(fig)
    return clean_svg(inject_svg_tooltips(buf.getvalue().decode('utf-8')))


def generate_normalised_overlay_chart(modules_list):
    """
    Generates an SVG line chart overlaying module grade distributions.
    Normalises cohort count to percentages.
    """
    if not modules_list:
        return ""

    bin_labels = ['AB', '0-9%', '10-19%', '20-29%', '30-39%', '40-49%', '50-59%', '60-69%', '70-79%', '80-89%', '90-100%']
    colors = ['#4361ee', '#ff006e', '#3a0ca3', '#7209b7', '#4cc9f0', '#ff7a59', '#10b981', '#f59e0b', '#64748b']

    from programme_analytics.views import calculate_module_analytics

    series_list = []
    for idx, m in enumerate(modules_list):
        scores = m.get('scores', [])
        if not scores:
            continue
        stats = calculate_module_analytics(scores, m.get('level', 4))
        n = stats['cohort_size']
        if n == 0:
            continue

        sb = stats['score_bins']
        y_vals = []
        y_vals.append((sb['absent'] / n) * 100.0)
        for b_count in sb['bins']:
            y_vals.append((b_count / n) * 100.0)

        color = colors[idx % len(colors)]
        point_urls = [
            f"tooltip:{m['module_code']} - {bl}: {y:.1f}% of cohort"
            for bl, y in zip(bin_labels, y_vals)
        ]
        series_list.append({
            'y_values': y_vals,
            'label': m['module_code'],
            'color': color,
            'marker': 'o',
            'linewidth': 2.0,
            'markersize': 6,
            'alpha': 0.85,
            'url': f"tooltip:{m['module_code']} - {m['module_title']}",
            'point_urls': point_urls
        })

    return generate_line_chart(
        x_labels=bin_labels,
        series_list=series_list,
        ylabel='% of Cohort',
        title=None,
        figsize=(10.0, 5.0),
        ylim=(-2, 105),
        grid_axis='y',
        grid_style='--',
        legend_loc='upper right',
        rotation=15,
        ha='right',
        fontsize_xticks=9.5,
        fontsize_yticks=9.5,
        fontsize_ylabel=12
    )


def generate_level_cohort_chart(level_data):
    """
    Generates an SVG bar chart comparing grade distributions across academic levels.
    """
    if not level_data:
        return ""

    level_data = sorted(level_data, key=lambda x: x['level'])

    levels = [f"Level {item['level']}" for item in level_data]
    pct_fail = [item.get('pct_fail', 0.0) for item in level_data]
    pct_3rd = [item.get('pct_3rd', 0.0) for item in level_data]
    pct_22 = [item.get('pct_22', 0.0) for item in level_data]
    pct_21 = [item.get('pct_21', 0.0) for item in level_data]
    pct_1st = [item.get('pct_1st', 0.0) for item in level_data]

    x = np.arange(len(levels))
    width = 0.15

    fig, ax = plt.subplots(figsize=(8.0, 4.5))

    fail_color = '#ef4444'
    third_color = '#f59e0b'
    two_two_color = '#8b5cf6'
    two_one_color = '#3b82f6'
    first_color = '#10b981'

    rects1 = ax.bar(x - 2 * width, pct_fail, width, label='Fail', color=fail_color, alpha=0.9, zorder=3)
    rects2 = ax.bar(x - width, pct_3rd, width, label='3rd Class', color=third_color, alpha=0.9, zorder=3)
    rects3 = ax.bar(x, pct_22, width, label='2:2 Class', color=two_two_color, alpha=0.9, zorder=3)
    rects4 = ax.bar(x + width, pct_21, width, label='2:1 Class', color=two_one_color, alpha=0.9, zorder=3)
    rects5 = ax.bar(x + 2 * width, pct_1st, width, label='1st Class', color=first_color, alpha=0.9, zorder=3)

    for bar, lvl in zip(rects1, levels):
        bar.set_url(f"tooltip:{lvl} Fail: {bar.get_height():.1f}%")
    for bar, lvl in zip(rects2, levels):
        bar.set_url(f"tooltip:{lvl} 3rd Class: {bar.get_height():.1f}%")
    for bar, lvl in zip(rects3, levels):
        bar.set_url(f"tooltip:{lvl} 2:2 Class: {bar.get_height():.1f}%")
    for bar, lvl in zip(rects4, levels):
        bar.set_url(f"tooltip:{lvl} 2:1 Class: {bar.get_height():.1f}%")
    for bar, lvl in zip(rects5, levels):
        bar.set_url(f"tooltip:{lvl} 1st Class: {bar.get_height():.1f}%")

    ax.set_ylabel('Percentage (%)', color='#475569', size=11, fontweight='semibold')
    ax.set_xticks(x)
    ax.set_xticklabels(levels, fontsize=10, fontweight='semibold')
    ax.set_ylim(0, 105)

    ax.grid(True, axis='y', color='#e2e8f0', linestyle='--', linewidth=0.8, zorder=0)
    ax.set_axisbelow(True)

    # Hide top, right, and left spines to match other charts
    for spine in ['top', 'right', 'left']:
        ax.spines[spine].set_visible(False)
    ax.spines['bottom'].set_color('#cbd5e1')

    # Disable tick markers to be consistent
    ax.tick_params(axis='both', which='both', length=0, colors='#475569', labelsize=10)
    ax.set_facecolor('white')
    fig.patch.set_facecolor('white')
    ax.legend(loc='upper right', fontsize=9.5, frameon=True, facecolor='white', edgecolor='#e2e8f0')

    buf = io.BytesIO()
    plt.savefig(buf, format='svg', bbox_inches='tight', transparent=False)
    plt.close(fig)

    svg_str = buf.getvalue().decode('utf-8')
    return inject_svg_tooltips(svg_str)


def generate_trend_line_chart(years, values, ylabel, title, color='#3b82f6'):
    """Generates a simple line chart with years on the x-axis."""
    point_urls = [f"tooltip:{yr}: {yi:.1f}" if yi is not None else "" for yr, yi in zip(years, values)]
    series = {
        'y_values': values,
        'color': color,
        'marker': 'o',
        'linewidth': 2.0,
        'markersize': 5,
        'point_urls': point_urls
    }
    
    ylim = None
    if values:
        min_v = min(values)
        max_v = max(values)
        if min_v == max_v:
            ylim = (max(0, min_v - 10), min_v + 10)
        else:
            padding = (max_v - min_v) * 0.15
            ylim = (max(0, min_v - padding), min_v + padding)

    return generate_line_chart(
        x_labels=years,
        series_list=[series],
        ylabel=ylabel,
        title=title,
        figsize=(4.5, 2.8),
        ylim=ylim,
        legend_loc='upper right',
        fontsize_xticks=8.5,
        fontsize_yticks=8.5,
        fontsize_ylabel=9.5,
        fontsize_title=10.5,
        pad_title=10
    )


def generate_sparkline_svg(values):
    """Generates a simple inline SVG sparkline line path."""
    if not values or len(values) < 2:
        return ""
    valid_vals = [v for v in values if v is not None]
    if len(valid_vals) < 2:
        return ""
    
    # SVG size: width=80, height=20
    w = 80
    h = 20
    
    # Add horizontal and vertical padding to prevent markers/lines from clipping
    pad_x = 4
    pad_y = 3
    
    min_v = min(valid_vals)
    max_v = max(valid_vals)
    span = max_v - min_v
    if span == 0:
        span = 1
        
    points = []
    dx = (w - 2 * pad_x) / (len(values) - 1)
    for i, val in enumerate(values):
        if val is None:
            continue
        cx = pad_x + i * dx
        cy = h - pad_y - ((val - min_v) / span) * (h - 2 * pad_y)
        points.append(f"{cx:.1f},{cy:.1f}")
        
    path_data = "M " + " L ".join(points)
    
    svg_str = f'<svg width="{w}" height="{h}" style="vertical-align: middle; overflow: visible;">'
    svg_str += f'<path d="{path_data}" fill="none" stroke="#3b82f6" stroke-width="2" />'
    
    # Highlight the last point (latest trend value)
    last_x = pad_x + (len(values) - 1) * dx
    last_val = values[-1]
    if last_val is not None:
        last_y = h - pad_y - ((last_val - min_v) / span) * (h - 2 * pad_y)
        svg_str += f'<circle cx="{last_x:.1f}" cy="{last_y:.1f}" r="3" fill="#ef4444" />'
    svg_str += '</svg>'
    return svg_str


def generate_module_trend_chart(code, years, history):
    """Generates a line chart for a single module showing Mean, Std. Dev., % 1st, % 2:1 & above, and % Fail."""
    means = [history[yr]['mean'] if yr in history else None for yr in years]
    std_devs = [history[yr]['std_dev'] if yr in history else None for yr in years]
    pct_1st = [history[yr]['pct_1st'] if yr in history else None for yr in years]
    pct_21 = [history[yr]['pct_21_above'] if yr in history else None for yr in years]
    pct_fail = [history[yr]['pct_fail'] if yr in history else None for yr in years]

    series_list = [
        {
            'y_values': means,
            'label': 'Mean Mark (%)',
            'color': '#3b82f6',
            'marker': 'o',
            'linewidth': 2.0,
            'markersize': 5,
            'point_urls': [f"tooltip:{yr} Mean: {val:.1f}%" if val is not None else "" for yr, val in zip(years, means)]
        },
        {
            'y_values': std_devs,
            'label': 'Std. Dev.',
            'color': '#f59e0b',
            'marker': 'd',
            'linewidth': 2.0,
            'markersize': 5,
            'point_urls': [f"tooltip:{yr} Std. Dev.: {val:.1f}" if val is not None else "" for yr, val in zip(years, std_devs)]
        },
        {
            'y_values': pct_1st,
            'label': '% 1st Class',
            'color': '#10b981',
            'marker': 's',
            'linewidth': 2.0,
            'markersize': 5,
            'point_urls': [f"tooltip:{yr} % 1st: {val:.1f}%" if val is not None else "" for yr, val in zip(years, pct_1st)]
        },
        {
            'y_values': pct_21,
            'label': '% 2:1 & above',
            'color': '#8b5cf6',
            'marker': 'p',
            'linewidth': 2.0,
            'markersize': 5,
            'point_urls': [f"tooltip:{yr} % 2:1 & Above: {val:.1f}%" if val is not None else "" for yr, val in zip(years, pct_21)]
        },
        {
            'y_values': pct_fail,
            'label': '% Fail',
            'color': '#ef4444',
            'marker': '^',
            'linewidth': 2.0,
            'markersize': 5,
            'point_urls': [f"tooltip:{yr} % Fail: {val:.1f}%" if val is not None else "" for yr, val in zip(years, pct_fail)]
        },
    ]

    return generate_line_chart(
        x_labels=years,
        series_list=series_list,
        ylabel='Percentage / Value',
        title=f"Performance Trends for {code}",
        figsize=(8.0, 3.8),
        ylim=(-5, 105),
        legend_loc='lower center',
        legend_bbox_to_anchor=(0.5, 1.02),
        legend_ncol=5,
        fontsize_xticks=9,
        fontsize_yticks=9,
        fontsize_ylabel=10,
        fontsize_title=11,
        pad_title=35
    )


def generate_programme_trend_chart(years, means, std_devs, pct_1sts, pct_21s, pct_fails):
    """Generates a single line chart showing all 5 programme-level performance trends across years."""
    series_list = [
        {
            'y_values': means,
            'label': 'Mean Mark (%)',
            'color': '#3b82f6',
            'marker': 'o',
            'linewidth': 2.5,
            'markersize': 6,
            'point_urls': [f"tooltip:{yr} Mean: {val:.1f}%" if val is not None else "" for yr, val in zip(years, means)]
        },
        {
            'y_values': std_devs,
            'label': 'Std. Dev.',
            'color': '#f59e0b',
            'marker': 'd',
            'linewidth': 2.5,
            'markersize': 6,
            'point_urls': [f"tooltip:{yr} Std. Dev.: {val:.1f}" if val is not None else "" for yr, val in zip(years, std_devs)]
        },
        {
            'y_values': pct_1sts,
            'label': '% 1st Class',
            'color': '#10b981',
            'marker': 's',
            'linewidth': 2.5,
            'markersize': 6,
            'point_urls': [f"tooltip:{yr} % 1st: {val:.1f}%" if val is not None else "" for yr, val in zip(years, pct_1sts)]
        },
        {
            'y_values': pct_21s,
            'label': '% 2:1 & above',
            'color': '#8b5cf6',
            'marker': 'p',
            'linewidth': 2.5,
            'markersize': 6,
            'point_urls': [f"tooltip:{yr} % 2:1 & Above: {val:.1f}%" if val is not None else "" for yr, val in zip(years, pct_21s)]
        },
        {
            'y_values': pct_fails,
            'label': '% Fail',
            'color': '#ef4444',
            'marker': '^',
            'linewidth': 2.5,
            'markersize': 6,
            'point_urls': [f"tooltip:{yr} % Fail: {val:.1f}%" if val is not None else "" for yr, val in zip(years, pct_fails)]
        },
    ]

    return generate_line_chart(
        x_labels=years,
        series_list=series_list,
        ylabel='Percentage / Value',
        title='Programme Performance Trends',
        figsize=(10.0, 4.5),
        ylim=(-5, 105),
        legend_loc='lower center',
        legend_bbox_to_anchor=(0.5, 1.02),
        legend_ncol=5,
        fontsize_xticks=10,
        fontsize_yticks=10,
        fontsize_ylabel=11,
        fontsize_title=12,
        pad_title=35
    )


def generate_scatter_plot(scores_x, scores_y, label_x, label_y, degree_level=None, r=None):
    """
    Generate a server-side SVG scatter plot comparing two assessment components' marks.
    Includes a linear trendline and horizontal/vertical pass threshold lines.
    """
    if not scores_x or not scores_y or len(scores_x) != len(scores_y):
        return ""

    is_m_level = bool(
        degree_level 
        and isinstance(degree_level, str) 
        and degree_level.strip().lower().startswith('m')
    )
    fail_threshold = 50 if is_m_level else 40

    # Separate submissions (both > 0) from non-submissions (either is 0)
    normal_x = []
    normal_y = []
    zero_x = []
    zero_y = []
    for x, y in zip(scores_x, scores_y):
        if x > 0 and y > 0:
            normal_x.append(x)
            normal_y.append(y)
        else:
            zero_x.append(x)
            zero_y.append(y)

    fig, ax = plt.subplots(figsize=(5.0, 4.5))

    # Scatter points - normal submissions in blue, non-submissions in red
    ax.scatter(normal_x, normal_y, color='#3b82f6', alpha=0.6, edgecolors='none', s=45, zorder=3)
    if zero_x:
        ax.scatter(zero_x, zero_y, color='#ef4444', alpha=0.6, edgecolors='none', s=45, zorder=3)

    # Plot trendline (Reduced Major Axis regression to align with the visual diagonal)
    if len(normal_x) >= 3 and r is not None:
        try:
            mean_x = np.mean(normal_x)
            mean_y = np.mean(normal_y)
            std_x = np.std(normal_x)
            std_y = np.std(normal_y)
            
            if std_x > 0 and std_y > 0:
                m = (std_y / std_x) if r >= 0 else -(std_y / std_x)
                c = mean_y - m * mean_x
                
                # Determine initial endpoints based on observed data range
                x1, x2 = float(min(normal_x)), float(max(normal_x))
                y1 = m * x1 + c
                y2 = m * x2 + c
                
                # Clip line endpoints so they stay within [0, 100] grid boundaries
                if y1 < 0:
                    x1 = (0.0 - c) / m
                    y1 = 0.0
                elif y1 > 100:
                    x1 = (100.0 - c) / m
                    y1 = 100.0
                    
                if y2 < 0:
                    x2 = (0.0 - c) / m
                    y2 = 0.0
                elif y2 > 100:
                    x2 = (100.0 - c) / m
                    y2 = 100.0
                    
                ax.plot([x1, x2], [y1, y2], color='#c8a951', linestyle='-', linewidth=2.0, zorder=4)
        except Exception:
            pass

    # Draw vertical & horizontal fail threshold lines
    ax.axvline(fail_threshold, color='#ef4444', linestyle='--', linewidth=1.2, alpha=0.7, zorder=2)
    ax.axhline(fail_threshold, color='#ef4444', linestyle='--', linewidth=1.2, alpha=0.7, zorder=2)

    # Label details inside chart
    if r is not None:
        ax.text(
            0.05, 0.95, f"r = {r:.2f}",
            transform=ax.transAxes,
            fontsize=11,
            fontweight='bold',
            color='#1a1a2e',
            va='top',
            bbox=dict(boxstyle='round,pad=0.3', facecolor='#f8fafc', edgecolor='#cbd5e1', alpha=0.9)
        )

    # Set axis limits & labels
    ax.set_xlim(-5, 105)
    ax.set_ylim(-5, 105)
    ax.set_xlabel(label_x, color='#475569', size=11, fontweight='semibold', fontfamily='DejaVu Sans')
    ax.set_ylabel(label_y, color='#475569', size=11, fontweight='semibold', fontfamily='DejaVu Sans')

    # Style grid and spines
    ax.grid(True, color='#e2e8f0', linestyle=':', linewidth=0.8, zorder=1)
    for spine in ['top', 'right']:
        ax.spines[spine].set_visible(False)
    for spine in ['left', 'bottom']:
        ax.spines[spine].set_color('#cbd5e1')
        ax.spines[spine].set_linewidth(1.0)

    ax.tick_params(axis='both', which='both', length=3, colors='#475569', labelsize=10)
    ax.set_facecolor('white')
    fig.patch.set_facecolor('white')

    buf = io.BytesIO()
    plt.savefig(buf, format='svg', bbox_inches='tight', transparent=False)
    plt.close(fig)

    return clean_svg(buf.getvalue().decode('utf-8'))

