# Generated by Django 5.2.8 on 2026-05-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('module_code', models.CharField(max_length=50)),
                ('module_title', models.CharField(max_length=200)),
                ('assessment_title', models.CharField(max_length=200)),
                ('weighting', models.IntegerField(help_text='Assessment weighting as percentage (e.g., 40 for 40%)')),
                ('max_marks', models.IntegerField(help_text='Maximum marks for the assessment (e.g., 100)')),
                ('categories', models.JSONField(default=list)),
                ('charts', models.JSONField(blank=True, default=list, help_text='Chart configurations for feedback sheet (e.g., histograms, radar charts)')),
                ('degree_level', models.CharField(choices=[('BEng', 'BEng'), ('MEng/MSc', 'MEng/MSc')], default='BEng', help_text='Degree level (BEng or MEng/MSc)', max_length=10)),
            ],
        ),
    ]
